# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

env:
  DOTNET_FRAMEWORK: "8.0"

on:
  [push, pull_request]
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

defaults:
  run:
    working-directory: ./bard

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DOTNET_FRAMEWORK}}.x
      - name: Test
        run: dotnet test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DOTNET_FRAMEWORK}}.x
      - name: Build
        run: dotnet build -c Release -f net${{env.DOTNET_FRAMEWORK}}
      - name: Upload artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4 #this does not use working-directory!!!
        with:
          path: bard/bard/bin/Release/net${{env.DOTNET_FRAMEWORK}}
          name: build
  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        runtime: [linux-x64, win-x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DOTNET_FRAMEWORK}}.x
      - name: Publish
        run: dotnet publish -c Release -f net${{env.DOTNET_FRAMEWORK}} -r ${{matrix.runtime}} -p:PublishSingleFile=true --self-contained true
      - name: Upload artifacts
        uses: actions/upload-artifact@v4 #this does not use working-directory!!!
        with:
          path: bard/bard/bin/Release/net${{env.DOTNET_FRAMEWORK}}/${{matrix.runtime}}/publish
          name: publish-${{matrix.runtime}}
